parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: var
    database_user: var
    database_password: var
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 916e368fc2ba7784d014c5767e57aa136c6afa24
    database_path: null
